version: '3.3'
services:
    #webform
    web:
        build:
            context: ./php
            dockerfile: Dockerfile    
        
        container_name: phpform
        depends_on:
            - db 
        volumes:
            - ./php:/var/www/html/
        ports:
            - 8008:80
    #database       
    db:
        container_name: mysqlform
        image: mysql:latest        
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: student_sample
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 6033:3306